services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    command:
      - scripts/start_app.sh
    ports:
      - "8001:8000"
    env_file: 
      - app.env
      - database.env
  
  database:
    image: postgres:11.12
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  
volumes:
  database-data: 