# Generated by Django 3.2.5 on 2021-07-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farewell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalutationValedictionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('farewell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greetings.farewell')),
                ('greeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greetings.greeting')),
            ],
        ),
        migrations.AddField(
            model_name='greeting',
            name='farewells',
            field=models.ManyToManyField(through='greetings.SalutationValedictionPair', to='greetings.Farewell'),
        ),
    ]
