# Generated by Django 3.2.5 on 2021-07-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GreetingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('initial_greeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_greeting', to='greetings.greeting')),
                ('responding_greeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responding_greeting', to='greetings.greeting')),
            ],
        ),
        migrations.AddField(
            model_name='greeting',
            name='related_greetings',
            field=models.ManyToManyField(related_name='_greetings_greeting_related_greetings_+', through='greetings.GreetingPair', to='greetings.Greeting'),
        ),
    ]
